# Generated by Django 3.2.18 on 2023-03-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230320_0756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recept',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveConstraint(
            model_name='recept',
            name='unique_recept',
        ),
    ]
